
mywebserver:
  build: ./nginx
  ports:
    - "80:80"
  links:
    - myweb:myweb
mydb:
  image: postgres:9.4.1
  ports:
    - "5432:5432"
  environment:
    -  POSTGRES_PASSWORD=password
  volumes:
    - ~/volumes/pgdata/etc:/etc/postgresql
    - ~/volumes/pgdata/log:/var/log/postgresql
    - ~/volumes/pgdata/data:/var/lib/postgresql/data
  # volumes:
    # - ./postgres-data:/var/lib/postgresql/data:z
myweb:
  build: .
  command: ./start.sh
  privileged: true
  tty: true
  stdin_open: true
  environment:
    - BUNDLE_PATH=/bundle
    - CHROMEDRIVER_PORT=4444
    - CHROMEDRIVER_WHITELISTED_IPS="0.0.0.0"
    - LANG=C.UTF-8
  links:
    - mydb
    - myrediserver
    - elasticsearch
  volumes:
    - .:/myapp
    - ~/.ssh:/root/.ssh
  volumes_from:
    - bundle
  ports:
    - "3000"
    - "4444:4444"
myrediserver:
  image: redis
  ports:
    - "6379:6379"
bundle:
  # 'image' will vary depending on your docker-compose
  # project name. You may need to run `docker-compose build web`
  # before this works.
  image: ubuntu
  volumes:
    - "~/volumes/mybundle:/bundle"
elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
  ports:
    - "9200:9200"
  environment:
    - "http.host=0.0.0.0" 
    - "transport.host=127.0.0.1"
kibana:
  image: docker.elastic.co/kibana/kibana:5.5.1
  links:
    - elasticsearch
  ports:
    - "5601:5601"
logstash:
  image: docker.elastic.co/logstash/logstash:5.5.1
  ports:
    - "5043:5043"
  links:
    -  elasticsearch
filebeats:
  build: filebeat
  # command: "chown 1000:1000 /usr/share/filebeat/filebeat.yml  && chmod go-w /usr/share/filebeat/filebeat.yml"
  volumes:
    - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
  volumes_from:
    - myweb
  links:
    - elasticsearch
metabase:
  image: metabase/metabase
  environment:
    - MB_DB_FILE=/tmp/metabase.db
  ports:
    - "5000:3000"
  volumes:
    - ~/volumes/metabase/tmp:/tmp
  links:
    - mydb



